from __future__ import annotations

import json
from pathlib import Path

from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter

from schema import Evidence, GroundedAnswer
from tools import keyword_tokens, read_text
from section3_rag import live_grounded_answer


ROOT = Path(__file__).resolve().parent
CORPUS = ROOT / "data" / "corpus"


def load_documents() -> list[Document]:
    documents = []
    for path in sorted(CORPUS.glob("*.txt")):
        documents.append(
            Document(
                page_content=read_text(path),
                metadata={"source_id": path.stem},
            )
        )
    return documents


def split_documents(documents: list[Document]) -> list[Document]:
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50,
    )
    return splitter.split_documents(documents)


def lexical_score(query: str, text: str) -> int:
    """Small classroom retriever score.

    This keeps the retrieval step small while still using LangChain Document
    and TextSplitter objects. The final answer is generated by the live LLM.
    In a real RAG system, replace lexical scoring with an embedding model plus
    a vector store retriever.
    """
    return len(keyword_tokens(query) & keyword_tokens(text))


def retrieve(query: str, chunks: list[Document], top_k: int = 2) -> list[Document]:
    ranked = sorted(
        chunks,
        key=lambda doc: lexical_score(query, doc.page_content),
        reverse=True,
    )
    return [doc for doc in ranked[:top_k] if lexical_score(query, doc.page_content) > 0]


def answer_question(query: str) -> GroundedAnswer:
    chunks = split_documents(load_documents())
    retrieved = retrieve(query, chunks)
    if not retrieved:
        return GroundedAnswer(
            answer_ko="제공된 문서에서 답을 찾을 수 없습니다.",
            not_answered=True,
        )

    evidence = [
        Evidence(
            source_id=doc.metadata["source_id"],
            quote=doc.page_content,
        )
        for doc in retrieved
    ]
    return live_grounded_answer(query, evidence)


def main() -> None:
    questions = [
        "support ticket triage는 어떤 fallback을 가져야 해?",
        "API onboarding guide에는 무엇이 들어가야 해?",
        "RAG 답변을 신뢰하기 전에 무엇을 확인해야 해?",
        "pricing 정보는 어디에 있어?",
    ]
    for question in questions:
        print("\nQUESTION:", question)
        print(json.dumps(answer_question(question).model_dump(), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
